services:
  - type: web
    name: daivies-ponto
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
